# Generated by Django 5.0.1 on 2024-02-01 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isimm', '0002_alter_article_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
    ]
